# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [2]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [3]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista)

Ejercicio 3: Suma los siguientes dos arrays

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

print(a + b)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [6]:
a = np.array([[4,2,2],
              [4,1,0]])

print(a * 0.2)

[[0.8 0.4 0.4]
 [0.8 0.2 0. ]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [7]:
a = np.array([x for x in range(9)])

print(a.shape)
print(a.reshape(3, 3))

(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [8]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

print(a.astype(int))

[[2 3 1]
 [4 2 1]]


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [9]:
a = np.eye(5)

a.astype(bool)

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

print(np.concatenate((a1, a2), axis=1))  # Concatenar horizontalmente

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejercicio 9: Cocatena de forma vertical los mismos array

In [ ]:
print(np.concatenate((a1, a2), axis=0))  # Concatenar verticalmente

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [17]:
even_array = np.array([x for x in range(100) if x % 2 == 0])

print(even_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [21]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

np.where(a > b)

(array([2, 4]),)

Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [34]:
equidistant_array = np.linspace(0, 100, 21)

print(equidistant_array)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [37]:
equal_matrix = np.full((2, 3), 23)

print(equal_matrix)

[[23 23 23]
 [23 23 23]]


Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [39]:
random_matrix = np.random.normal(0, 1, (8, 2))

print(random_matrix)


[[ 1.52428591  1.14712989]
 [ 0.34257164  1.0132521 ]
 [ 1.21631333 -0.6067728 ]
 [ 0.50579195  1.2455236 ]
 [-0.9587664  -0.80139258]
 [ 1.61831735  1.17677524]
 [-0.17439661  1.37603105]
 [ 0.71194382 -1.10386288]]


Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [44]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

print(np.cross(a, b))

print(a @ b)

print(np.dot(a, b))

print(a * b)

[[-1  2 -1]
 [-1  2 -1]
 [-1  2 -1]]
[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [49]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

print(np.sort(a))

print(np.sort(a)[::-1])

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]
[1101  939  923  387  299  292  199   91   82   38    2    2    1    0]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [ ]:
# Leer el csv venta_libros en un array
data = np.genfromtxt('./datasets/venta_libros.csv', delimiter=',', skip_header=1, dtype=int)

year = data[:, 0]
month = data[:, 1]
books = data[:, 2]

print(year)
print(month)
print(books)

[[2019    2  400]
 [2019    3  339]
 [2019    4  389]
 [2019    5  141]
 [2019    6  332]
 [2019    7  386]
 [2019    8  307]
 [2019    9  304]
 [2019   10  167]
 [2019   11  133]
 [2019   12  151]
 [2020    1  276]
 [2020    2   57]
 [2020    3  125]
 [2020    4   27]
 [2020    5  222]
 [2020    6  363]
 [2020    7   26]
 [2020    8  162]
 [2020    9  383]
 [2020   10  383]
 [2020   11  179]
 [2020   12  386]
 [2021    1  432]
 [2021    2  482]
 [2021    3  202]
 [2021    4  115]
 [2021    5  420]
 [2021    6   87]
 [2021    7   36]
 [2021    8  489]
 [2021    9  440]
 [2021   10   83]
 [2021   11  258]
 [2021   12  281]
 [2022    1  393]
 [2022    2  227]
 [2022    3  236]
 [2022    4  453]
 [2022    5  359]
 [2022    6  252]
 [2022    7   57]
 [2022    8  473]
 [2022    9  331]
 [2022   10  349]
 [2022   11  212]
 [2022   12  131]]
[2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 2020 2020 2020
 2020 2020 2020 2020 2020 2020 2020 2020 2020 2021 2021 2021 2021 2021
 2021 2021 

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [ ]:
print(f"El valor máximo de ventas de libros es {np.max(books)} y ocurrió en el mes {month[np.argmax(books)]} en el año {year[np.argmax(books)]}")

489
30
El valor máximo de ventas de libros es 489 y ocurrió en el mes 8 en el año 2021


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [60]:
print(f"Las ventas totales de libros fueron {np.sum(books)}")
print(f"El promedio de ventas de libros fue {np.mean(books)}")
print(f"La mediana de ventas de libros fue {np.median(books)}")
print(f"La desviación estándar de ventas de libros fue {np.std(books)}")

Las ventas totales de libros fueron 12436
El promedio de ventas de libros fue 264.59574468085106
La mediana de ventas de libros fue 276.0
La desviación estándar de ventas de libros fue 136.14223781788837
